// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mobile_App.Models;

namespace Mobile_App.Migrations
{
    [DbContext(typeof(MobileShopDbContext))]
    partial class MobileShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Mobile_App.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("hoTen")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("maLoaiNguoiDung")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("matKhau")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("soDt")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("taiKhoan")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
